# inputs
dataset_yaml_v12: "configs/datasets/dataset_nanoAODv12_run3.yaml"
dataset_yaml_v15: "configs/datasets/dataset_nanoAODv15_run3.yaml"

# what to run
# years: ["2022preEE", "2022postEE", "2023", "2023BPix", "2024"]
years: ["2024"]
nanoAODv: "15"   # or "15"
label_suffix: "15Feb_FilterJetsHorn30GeV_JEROff"


# dask gateway
use_gateway: true
cluster_index: 1

# zpt DNN
zpt:
  outbase: "zpt_wgt_dnn"
  max_events: 3000000
  batch: 65536
