import os


configfile: "workflow/config.yaml"

HMM_BASE = config.get("hmm_base", f"/work/projects/hmm")
HMM_USER = os.environ["USER"]

USE_EXISTING_STAGE1 = config.get("use_existing_stage1", False)

YEARS = config["years"]
RUN_TAG = config.get("run_tag", "default")

LOGDIR = f"logs/{RUN_TAG}"
STATEDIR = f"state/{RUN_TAG}"
FAIL_LOG = f"{LOGDIR}/failed_jobs.log"

os.makedirs(LOGDIR, exist_ok=True)
with open(FAIL_LOG, "w", encoding="utf-8"):
    pass

REPEATS = ["1"] # In case some jobs fails for the stage-1, so to recover it run the stage-1 three times. All followed dependents will depend on the "3"
FINAL_REP = REPEATS[-1]

ZPT_JETS_CATS = ["0", "1", "2"]

PLOT_CATS = ["nocat", "vbf", "ggh"]
# PLOT_CATS = ["vbf", "ggh"]
# PLOT_CATS = ["vbf"]
# PLOT_CATS = ["nocat"]

# PLOT_NJETS = ["inclusive", "0", "1", "2"]   # adapt to what your script accepts
# PLOT_NJETS = ["0", "1", "2"]   # adapt to what your script accepts
PLOT_NJETS = ["inclusive"]   # adapt to what your script accepts

JJ_ETA_REGIONS = [
    "all",
    "jj_both_central",
    # "jj_non_central",
    # "jj_one_fwd25_one_central",
    # "jj_one_he_one_central",
    # "jj_one_fwd30_one_central",
    # "jj_both_fwd25",
    # "jj_both_he",
    # "jj_both_fwd30",
    # "jj_one_he_one_fwd30",
]
PLOT_ZPT_MODES  = ["nozpt"] # ["withzpt", "nozpt"]
# PLOT_ZPT_MODES  = ["withzpt", "nozpt"] # ["withzpt", "nozpt"]
PLOT_VAR_SETS   = ["fullset"]          # ["minset", "fullset"]

wildcard_constraints:
    year="|".join([str(y) for y in YEARS]),
    rep="|".join(REPEATS),
    cat="|".join(PLOT_CATS),
    njets="|".join(ZPT_JETS_CATS),
    njets_plot = "|".join(PLOT_NJETS),
    zpt_mode   = "|".join(PLOT_ZPT_MODES),
    var_set    = "|".join(PLOT_VAR_SETS),
    jj_eta_region = "|".join(JJ_ETA_REGIONS),

RUN2_YEARS = ["2016preVFP", "2016postVFP", "2017", "2018"]
RUN3_YEARS = ["2022preEE", "2022postEE", "2023", "2023BPix", "2024", "2025"]
YEAR_META = {
    "2016preVFP": ("run2", "15"),
    "2016postVFP": ("run2", "15"),
    "2017": ("run2", "15"),
    "2018": ("run2", "15"),
    "2022preEE": ("run3", "12"),
    "2022postEE": ("run3", "12"),
    "2023": ("run3", "12"),
    "2023BPix": ("run3", "12"),
    "2024": ("run3", "15"),
    "2025": ("run3", "15"),
}

DATASET_YAMLS = {
    ("run2", "12"): "configs/datasets/dataset_nanoAODv12_run2.yaml",
    ("run2", "15"): "configs/datasets/dataset_nanoAODv15_run2.yaml",
    ("run3", "15"): "configs/datasets/dataset_nanoAODv15_run3.yaml",
    ("run3", "12"): "configs/datasets/dataset_nanoAODv12_run3.yaml",
}


def nano_for_year(year: str) -> str:
    try:
        return YEAR_META[year][1]
    except KeyError as e:
        raise ValueError(f"nano_for_year: unknown year '{year}'") from e


def yaml_for_year(year: str) -> str:
    try:
        era, nano = YEAR_META[year]
    except KeyError as e:
        raise ValueError(f"yaml_for_year: unknown year '{year}'") from e

    try:
        return DATASET_YAMLS[(era, nano)]
    except KeyError as e:
        raise ValueError(
            f"No dataset YAML for era={era}, nano={nano} (year={year})"
        ) from e


def label_for_year(year: str) -> str:
    era, nano = YEAR_META[year]
    # nano = "12"
    era_tag = "Run2" if era == "run2" else "Run3"
    return f"{era_tag}_nanoAODv{nano}_{RUN_TAG}"


def plot_base_for_year(year: str) -> str:
    era, nano = YEAR_META[year]
    # nano = "12"
    era_tag = "Run2" if era == "run2" else "Run3"
    return f"validation/figs/{era_tag}_nanoAODv{nano}"


USE_GW = bool(config.get("use_gateway", False))
CLIDX  = str(config.get("cluster_index", 0))

ZPT = config["zpt"]
ZPT_OUT = ZPT.get("outbase", "try_zpt_dnn")
ZPT_MAXEV = int(ZPT.get("max_events", 3000000))
ZPT_BATCH = int(ZPT.get("batch", 65536))


def gw_flags():
    return f"-k -i {CLIDX}" if USE_GW else ""


def gw_flags_plots():
    return f" --use_gateway --cluster_index {CLIDX} " if USE_GW else ""

PLOT_TARGETS = [
    (year, cat, njets_plot, jj_eta_region, zpt_mode, var_set)
    for year in YEARS
    for cat in PLOT_CATS
    for njets_plot in PLOT_NJETS
    for jj_eta_region in JJ_ETA_REGIONS
    for zpt_mode in PLOT_ZPT_MODES
    for var_set in PLOT_VAR_SETS
    if not (cat == "vbf" and njets_plot != "inclusive")
]
PLOT_DONE = expand(
    STATEDIR + "/plots_{year}_{cat}_{njets_plot}_{jj_eta_region}_{zpt_mode}_{var_set}.done",
    zip,
    year=[x[0] for x in PLOT_TARGETS],
    cat=[x[1] for x in PLOT_TARGETS],
    njets_plot=[x[2] for x in PLOT_TARGETS],
    jj_eta_region=[x[3] for x in PLOT_TARGETS],
    zpt_mode=[x[4] for x in PLOT_TARGETS],
    var_set=[x[5] for x in PLOT_TARGETS],
)

INITIAL_STAGE1_DONE = [] if USE_EXISTING_STAGE1 else expand(
    STATEDIR + "/stage1_{year}_rep{rep}.done",
    year=YEARS,
    rep=REPEATS,
)
INITIAL_STAGE1_COMPACT_DONE = [] if USE_EXISTING_STAGE1 else expand(
    STATEDIR + "/stage1_compact_{year}.done",
    year=YEARS,
)

rule all:
    input:
        # (1) stage1 for all years
        INITIAL_STAGE1_DONE,
        # (2) stage1Compact for all years
        INITIAL_STAGE1_COMPACT_DONE,
        # (3) plotter (after stage1)
        PLOT_DONE,
        # (4) get zpt
        expand(STATEDIR + "/zpt_step0_{year}.done", year=YEARS),
        expand(STATEDIR + "/zpt_step1_{year}_njets{njets}.done", year=YEARS, njets=ZPT_JETS_CATS),
        expand(STATEDIR + "/zpt_step2_{year}_njets{njets}.done", year=YEARS, njets=ZPT_JETS_CATS),
        # (5) get EBE mass calibration
        expand(STATEDIR + "/mass_calibration_Data_{year}.done", year=YEARS),
        expand(STATEDIR + "/mass_calibration_Data_Closure_{year}.done", year=YEARS),
        expand(STATEDIR + "/mass_calibration_MC_{year}.done", year=YEARS),
        expand(STATEDIR + "/mass_calibration_MC_Closure_{year}.done", year=YEARS),
        f"{STATEDIR}/summary.done"

rule plot_all:
    input:
        # (2) stage1Compact for all years
        # expand(STATEDIR + "/stage1_compact_{year}.done", year=YEARS),
        # (3) plotter (after stage1)
        PLOT_DONE,


rule all_stage1:
    input:
        # (1) stage1 for all years
        INITIAL_STAGE1_DONE,
        # (2) stage1Compact for all years
        INITIAL_STAGE1_COMPACT_DONE,
        # (3) plotter (after stage1)
        PLOT_DONE,
        # f"{STATEDIR}/summary.done"



# ---------------------------------------
# 1) Stage-1 (all samples)
# ---------------------------------------
rule stage1:
    output:
        done=STATEDIR + "/stage1_{year}_rep{rep}.done",
    log:
        LOGDIR + "/stage1_{year}_rep{rep}.log",
    params:
        logdir=LOGDIR,
        statedir=STATEDIR,
        nano=lambda wc: nano_for_year(wc.year),
        yaml=lambda wc: yaml_for_year(wc.year),
        label=lambda wc: label_for_year(wc.year),
        gw=lambda wc: gw_flags(),
        summary=lambda wc: (
            f"{HMM_BASE}/{HMM_USER}/hmm_ntuples/copperheadV1clean/"
            f"{label_for_year(wc.year)}/stage1_output/{wc.year}/"
            "_status/stage1_summary.log"
        ),
    resources:
        gateway=1,
    shell:
        r"""
        set -euo pipefail
        set -x
        mkdir -p {params.logdir} {params.statedir}
        ts=$(date +"%Y-%m-%d_%H-%M-%S")
        PYTHONUNBUFFERED=1 bash run_analysis_pipeline.sh \
          -c {params.yaml} \
          -v {params.nano} \
          -l {params.label} \
          -y "{wildcards.year}" \
          -m 1 \
          {params.gw}  \
          > {log} 2>&1
        summary="{params.summary}"

        # Rename log file after running the command, as Snakemake
        # delets the log file before running the command.
        LOGFILE="{log}"
        if [[ -f "$LOGFILE" ]]; then
            echo "Rotating existing log → $LOGFILE.attempt_${{ts}}"
            cp "$LOGFILE" "$LOGFILE.attempt_${{ts}}"
        else
            echo "No previous log found (first run)"
        fi

        if [[ ! -f "$summary" ]]; then
            echo "ERROR: stage1 summary log not found: $summary"
            echo "{rule} {wildcards} ATTEMPT  FAILED" >> {FAIL_LOG}
            exit 1
        fi

        failed=$(sed -n '2p' "$summary" | awk '{{print $4}}' )
        echo "failed: ${{failed}}"

        if [[ "$failed" != "0" ]]; then
            echo "ERROR: Stage1 summary indicates FAILED count: ${{failed}}"
            echo "{rule} {wildcards} ATTEMPT  FAILED" >> {FAIL_LOG}
            exit 1
        fi

        echo "Stage1 completed successfully"
        echo "{rule} {wildcards} SUCCESS attempt time stamp: ${{ts}}" >> {FAIL_LOG}
        touch {output.done}
        """


# ---------------------------------------
# 2) Compact Stage-1 Outputs
# ---------------------------------------
rule stage1Compact:
    input:
        STATEDIR + f"/stage1_{{year}}_rep{FINAL_REP}.done"
    output:
        done=STATEDIR + "/stage1_compact_{year}.done",
    log:
        LOGDIR + "/stage1_compact_{year}.log",
    params:
        logdir=LOGDIR,
        statedir=STATEDIR,
        nano=lambda wc: nano_for_year(wc.year),
        yaml=lambda wc: yaml_for_year(wc.year),
        label=lambda wc: label_for_year(wc.year),
        gw=lambda wc: gw_flags(),
        outpath=lambda wc: (
            f"{HMM_BASE}/{HMM_USER}/hmm_ntuples/copperheadV1clean/"
            f"{label_for_year(wc.year)}/stage1_output/{wc.year}"
        ),
    resources:
        gateway=1,
    shell:
        r"""
        set -euo pipefail
        set -x
        mkdir -p {params.logdir} {params.statedir}
        PYTHONUNBUFFERED=1 bash run_analysis_pipeline.sh \
            -c {params.yaml} \
            -v {params.nano} \
            -l {params.label} \
            -y "{wildcards.year}" \
            -m compact \
            {params.gw} \
            > {log} 2>&1

        # -----------------------------
        # Validation block
        # -----------------------------
        BASE="{params.outpath}"
        if ! python3 scripts/compact_sanity_check.py --base "$BASE"; then
            echo "{rule} {wildcards} ATTEMPT  FAILED" >> {FAIL_LOG}
            echo "stage1Compact year={wildcards.year} attempt= FAILED" >> {FAIL_LOG}
            exit 1
        fi

        echo "{rule} {wildcards} SUCCESS attempt=" >> {FAIL_LOG}
        touch {output.done}
        """


# ---------------------------------------
# 3) Plotter (depends on stage1 outputs)
# ---------------------------------------
rule plots:
    input:
        lambda wc: [] if USE_EXISTING_STAGE1 else [
            STATEDIR + f"/stage1_compact_{wc.year}.done"
        ]
    output:
        done=STATEDIR + "/plots_{year}_{cat}_{njets_plot}_{jj_eta_region}_{zpt_mode}_{var_set}.done",
    log:
        LOGDIR + "/plots_{year}_{cat}_{njets_plot}_{jj_eta_region}_{zpt_mode}_{var_set}.log",
    params:
        logdir=LOGDIR,
        statedir=STATEDIR,
        gw=lambda wc: gw_flags_plots(),
        load_path=lambda wc: (
            f"{HMM_BASE}/{HMM_USER}/hmm_ntuples/copperheadV1clean/"
            f"{label_for_year(wc.year)}/stage1_output/{wc.year}/f1_0"
        ),
        save_path=lambda wc: (
            f"{plot_base_for_year(wc.year)}/"
            f"{label_for_year(wc.year)}/VBFfilter_False/"
        ),
        # map wildcards -> CLI flags
        zpt_flag=lambda wc: "--remove_zpt_weights" if wc.zpt_mode == "nozpt" else "",
        minset_flag=lambda wc: "--minimum_set" if wc.var_set == "minset" else "",
    # resources:
    #     gateway=1
    shell:
        r"""
        set -euo pipefail
        set -x
        mkdir -p {params.logdir} {params.statedir}

        PYTHONUNBUFFERED=1 \
        python plotter/validation_plotter_unified.py \
            -y {wildcards.year} \
            --save_path {params.save_path} \
            --load {params.load_path} \
            --use-compacted "compacted" \
            -cat {wildcards.cat} \
            {params.gw} \
            --njets {wildcards.njets_plot} \
            --jj-eta-region "{wildcards.jj_eta_region}" \
            --region h-sidebands z-peak \
            {params.minset_flag} \
            {params.zpt_flag} \
            > {log} 2>&1

        #    --use_dnn_zpt_weights \
        #    --vbf_filter_study \

        # ---- SUCCESS CHECK ----
        if grep -q "Plots are saved to " {log}; then
            echo "Plot job successful."
            echo "{rule} {wildcards} SUCCESS attempt=" >> {FAIL_LOG}
            touch {output.done}
        else
            echo "ERROR: Plot job did not complete successfully."
            echo "Success string not found in log."
            echo "{rule} {wildcards} ATTEMPT  FAILED" >> {FAIL_LOG}
            exit 1
        fi
        """

# ---------------------------------------
# 4) ZpT weight computation (stage-0: Just prepare root files for data/mc for fitting) (depends on stage1 outputs)
# ---------------------------------------
rule zpt0:
    input:
       lambda wc: [] if USE_EXISTING_STAGE1 else [
           STATEDIR + f"/stage1_compact_{wc.year}.done"
       ],
    output:
        done=STATEDIR + "/zpt_step0_{year}.done",
    log:
        LOGDIR + "/zpt_step0_{year}.log",
    params:
        logdir=LOGDIR,
        statedir=STATEDIR,
        nano=lambda wc: nano_for_year(wc.year),
        yaml=lambda wc: yaml_for_year(wc.year),
        label=lambda wc: label_for_year(wc.year),
        gw=lambda wc: gw_flags(),
    resources:
        gateway=1,
    shell:
        r"""
        set -euo pipefail
        set -x
        mkdir -p {params.logdir} {params.statedir}
        PYTHONUNBUFFERED=1 bash run_analysis_pipeline.sh \
          -c {params.yaml} \
          -v {params.nano} \
          -l {params.label} \
          -y "{wildcards.year}" \
          -m zpt_fit0 \
          {params.gw} \
          > {log} 2>&1
        echo "{rule} {wildcards} SUCCESS attempt=" >> {FAIL_LOG}
        touch {output.done}
        """


# ---------------------------------------
# 5) ZpT weight computation (stage-1: Run the f-test) (depends on zpt0 outputs)
# ---------------------------------------
rule zpt1:
    input:
       STATEDIR + "/zpt_step0_{year}.done",
    output:
        done=STATEDIR + "/zpt_step1_{year}_njets{njets}.done",
    log:
        LOGDIR + "/zpt_step1_{year}_njets{njets}.log",
    params:
        logdir=LOGDIR,
        statedir=STATEDIR,
        nano=lambda wc: nano_for_year(wc.year),
        yaml=lambda wc: yaml_for_year(wc.year),
        label=lambda wc: label_for_year(wc.year),
        gw=lambda wc: gw_flags(),
    shell:
        r"""
        set -euo pipefail
        set -x
        mkdir -p {params.logdir} {params.statedir}
        PYTHONUNBUFFERED=1 bash run_analysis_pipeline.sh \
          -c {params.yaml} \
          -v {params.nano} \
          -l {params.label} \
          -y "{wildcards.year}" \
          -m zpt_fit1 \
          -n {wildcards.njets} \
          {params.gw} \
          > {log} 2>&1
        echo "{rule} {wildcards} SUCCESS attempt=" >> {FAIL_LOG}
        touch {output.done}
        """


# ---------------------------------------
# 6) ZpT weight computation (stage-2: Run the final polyfit and obtain final function parameters and save it in YAML file) (depends on zpt1 outputs)
# ---------------------------------------
rule zpt2:
    input:
       STATEDIR + "/zpt_step1_{year}_njets{njets}.done",
    output:
        done=STATEDIR + "/zpt_step2_{year}_njets{njets}.done",
    log:
        LOGDIR + "/zpt_step2_{year}_njets{njets}.log",
    params:
        logdir=LOGDIR,
        statedir=STATEDIR,
        nano=lambda wc: nano_for_year(wc.year),
        yaml=lambda wc: yaml_for_year(wc.year),
        label=lambda wc: label_for_year(wc.year),
        gw=lambda wc: gw_flags(),
    shell:
        r"""
        set -euo pipefail
        set -x
        mkdir -p {params.logdir} {params.statedir}
        PYTHONUNBUFFERED=1 bash run_analysis_pipeline.sh \
          -c {params.yaml} \
          -v {params.nano} \
          -l {params.label} \
          -y "{wildcards.year}" \
          -m zpt_fit2 \
          -n {wildcards.njets} \
          {params.gw} \
          > {log} 2>&1
        echo "{rule} {wildcards} SUCCESS attempt=" >> {FAIL_LOG}
        touch {output.done}
        """


# ---------------------------------------
# 7) EBE mass calibration
# ---------------------------------------
rule MassCalibrationMC:
    input:
       lambda wc: [] if USE_EXISTING_STAGE1 else [
           STATEDIR + f"/stage1_compact_{wc.year}.done"
       ],
    output:
        done=STATEDIR + "/mass_calibration_MC_{year}.done",
    log:
        LOGDIR + "/mass_calibration_MC_{year}.log",
    params:
        logdir=LOGDIR,
        statedir=STATEDIR,
        nano=lambda wc: nano_for_year(wc.year),
        yaml=lambda wc: yaml_for_year(wc.year),
        label=lambda wc: label_for_year(wc.year),
        gw=lambda wc: gw_flags(),
    resources:
        gateway=1,
    shell:
        r"""
        set -euo pipefail
        set -x
        mkdir -p {params.logdir} {params.statedir}
        PYTHONUNBUFFERED=1 bash run_analysis_pipeline.sh \
          -c {params.yaml} \
          -v {params.nano} \
          -l {params.label} \
          -y "{wildcards.year}" \
          -M 1 \
          -p "V1" \
          -m calib  \
          {params.gw}  \
          > {log} 2>&1
        echo "{rule} {wildcards} SUCCESS attempt=" >> {FAIL_LOG}
        touch {output.done}
        """


rule MassCalibrationMCClosure:
    input:
       STATEDIR + "/mass_calibration_MC_{year}.done",
    output:
        done=STATEDIR + "/mass_calibration_MC_Closure_{year}.done",
    log:
        LOGDIR + "/mass_calibration_MC_Closure_{year}.log",
    params:
        logdir=LOGDIR,
        statedir=STATEDIR,
        nano=lambda wc: nano_for_year(wc.year),
        yaml=lambda wc: yaml_for_year(wc.year),
        label=lambda wc: label_for_year(wc.year),
        gw=lambda wc: gw_flags(),
    resources:
        gateway=1,
    shell:
        r"""
        set -euo pipefail
        set -x
        mkdir -p {params.logdir} {params.statedir}
        PYTHONUNBUFFERED=1 bash run_analysis_pipeline.sh \
          -c {params.yaml} \
          -v {params.nano} \
          -l {params.label} \
          -y "{wildcards.year}" \
          -M 1 \
          -p "V1" \
          -m calib_closure  \
          {params.gw}  \
          > {log} 2>&1
        echo "{rule} {wildcards} SUCCESS attempt=" >> {FAIL_LOG}
        touch {output.done}
        """


rule MassCalibrationData:
    input:
       lambda wc: [] if USE_EXISTING_STAGE1 else [
           STATEDIR + f"/stage1_compact_{wc.year}.done"
       ],
    output:
        done=STATEDIR + "/mass_calibration_Data_{year}.done",
    log:
        LOGDIR + "/mass_calibration_Data_{year}.log",
    params:
        logdir=LOGDIR,
        statedir=STATEDIR,
        nano=lambda wc: nano_for_year(wc.year),
        yaml=lambda wc: yaml_for_year(wc.year),
        label=lambda wc: label_for_year(wc.year),
        gw=lambda wc: gw_flags(),
    resources:
        gateway=1,
    shell:
        r"""
        set -euo pipefail
        set -x
        mkdir -p {params.logdir} {params.statedir}
        PYTHONUNBUFFERED=1 bash run_analysis_pipeline.sh \
          -c {params.yaml} \
          -v {params.nano} \
          -l {params.label} \
          -y "{wildcards.year}" \
          -M 0 \
          -p "V1" \
          -m calib \
          {params.gw}  \
          > {log} 2>&1
        echo "{rule} {wildcards} SUCCESS attempt=" >> {FAIL_LOG}
        touch {output.done}
        """


rule MassCalibrationDataClosure:
    input:
       STATEDIR + "/mass_calibration_Data_{year}.done",
    output:
        done=STATEDIR + "/mass_calibration_Data_Closure_{year}.done",
    log:
        LOGDIR + "/mass_calibration_Data_Closure_{year}.log",
    params:
        logdir=LOGDIR,
        statedir=STATEDIR,
        nano=lambda wc: nano_for_year(wc.year),
        yaml=lambda wc: yaml_for_year(wc.year),
        label=lambda wc: label_for_year(wc.year),
        gw=lambda wc: gw_flags(),
    resources:
        gateway=1,
    shell:
        r"""
        set -euo pipefail
        set -x
        mkdir -p {params.logdir} {params.statedir}
        PYTHONUNBUFFERED=1 bash run_analysis_pipeline.sh \
          -c {params.yaml} \
          -v {params.nano} \
          -l {params.label} \
          -y "{wildcards.year}" \
          -M 0 \
          -p "V1" \
          -m calib_closure \
          {params.gw}  \
          > {log} 2>&1
        echo "{rule} {wildcards} SUCCESS attempt=" >> {FAIL_LOG}
        touch {output.done}
        """


rule summary:
    input:
        expand(STATEDIR + "/stage1_{year}_rep{rep}.done", year=YEARS, rep=REPEATS),
        expand(STATEDIR + "/stage1_compact_{year}.done", year=YEARS),
        expand(STATEDIR + "/zpt_step0_{year}.done", year=YEARS),
        #expand(STATEDIR + "/mass_calibration_Data_{year}.done", year=YEARS),
    output:
        f"{STATEDIR}/summary.done"
    shell:
        r"""
        echo "=============================="
        echo " FINAL JOB SUMMARY"
        echo "=============================="

        if [[ -f {FAIL_LOG} ]]; then
            echo ""
            echo "FAILED JOBS:"
            cat {FAIL_LOG} | grep FAILED || true

            nfail=$(grep -c FAILED {FAIL_LOG} || true)
        else
            nfail=0
        fi

        nsuccess=$(grep -c SUCCESS {FAIL_LOG} || true)

        echo ""
        echo "SUCCESS: $nsuccess"
        echo "FAILED:  $nfail"

        if [[ "$nfail" -ne 0 ]]; then
            echo "Some jobs failed"
            exit 1
        else
            echo "All jobs successful"
        fi

        touch {output}
        """
