[workspace]
authors = ["ram1123 <ramkrishna.sharma71@gmail.com>"]
channels = ["conda-forge", "pytorch", "nvidia"]
name = "coffea_latest_ml"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.12.9"
pip = "*"
coffea = "==2025.3.0"
awkward = "*"
uproot = "*"
hist = "*"
mplhep = "*"
uncertainties = "*"
lmfit = "*"
correctionlib = "==2.6.4"
hepconvert = "*"
root = "==6.32.2"
root_base = "==6.32.2"
xgboost = "*"
dask = "*"
dask-gateway = "*"
dask-awkward = "==2025.5.0"
xrootd = "*"
ipywidgets = "*"
ipykernel = "*"
omegaconf = "*"
seaborn = "*"
libnvjitlink-dev = "*"
pytorch = "2.5.*"
pytorch-cuda = "12.4.*"
scikit-learn = "*"
numpy = "*"
matplotlib = "*"
plotly = "*"

[pypi-dependencies]
rucio-clients = "*"
fsspec-xrootd = "*"
torch = "*"
cmsstyle = "*"
scikit-hep-testdata = "*"
graphviz = "*"
ax-platform = ">=1.2.1, <2"
shap = ">=0.50.0, <0.51"

[activation]
scripts = ["scripts/pixi_activate.sh"]
