# configs/features.yaml

regions:

  central:
    - chEmEF
    - chHEF
    - neEmEF
    - neHEF
    - muEF
    - nConstituents
    - mass
    - area
    - rawFactor

  HE:
    - chEmEF
    - chHEF
    - neEmEF
    - neHEF
    - muEF
    - nConstituents
    - mass
    - area
    - rawFactor

  HEpos:
    - chEmEF
    - chHEF
    - neEmEF
    - neHEF
    - muEF
    - nConstituents
    - mass
    - area
    - rawFactor

  HEneg:
    - chEmEF
    - chHEF
    - neEmEF
    - neHEF
    - muEF
    - nConstituents
    - mass
    - area
    - rawFactor

  HF:
    - hfcentralEtaStripSize
    - hfadjacentEtaStripsSize
    - hfsigmaEtaEta
    - hfsigmaPhiPhi
    - hf_ratio
    - hf_sigma_sum
    - mass
    - rawFactor
    - area

  HFpos:
    - hfcentralEtaStripSize
    - hfadjacentEtaStripsSize
    - hfsigmaEtaEta
    - hfsigmaPhiPhi
    - hf_ratio
    - hf_sigma_sum
    - mass
    - rawFactor
    - area

  HFneg:
    - hfcentralEtaStripSize
    - hfadjacentEtaStripsSize
    - hfsigmaEtaEta
    - hfsigmaPhiPhi
    - hf_ratio
    - hf_sigma_sum
    - mass
    - rawFactor
    - area
