data:
    "2016preVFP": [data_B, data_C, data_D, data_E, data_F]
    "2016postVFP": [data_F, data_G, data_H]
    "2016": [data_B, data_C, data_D, data_E, data_F, data_G, data_H]
    "2017": [data_B, data_C, data_D, data_E, data_F]
    "2018": [data_A, data_B, data_C, data_D]
    run2: [data_A, data_B, data_C, data_D, data_E, data_F, data_G, data_H]

    "2022preEE": [data_C, data_D]
    "2022postEE": [data_E, data_F, data_G]
    "2023": [data_C]
    "2023BPix": [data_D]
    "2024": [data_C, data_D, data_E, data_F, data_G, data_H, data_I]
    run3: [data_C, data_D, data_E, data_F, data_G, data_H, data_I]

# --------------------------------------------------

background:
    label: 0

    groups:
        DY:
            processes:
                - dyTo2L_M-50_incl
            processes_per_year:
                2025:
                    - dyTo2Mu_M-50_aMCatNLO
                2024:
                    - dyTo2Mu_M-50_aMCatNLO
                2018:
                    - dyTo2Mu_M-50_MiNNLO
                    - dyTo2Mu_M-100to200_MiNNLO
                2017:
                    - dyTo2Mu_M-50_MiNNLO
                    - dyTo2Mu_M-100to200_MiNNLO
                2016postVFP:
                    - dyTo2Mu_M-50_MiNNLO
                    - dyTo2Mu_M-100to200_MiNNLO
                2016preVFP:
                    - dyTo2Mu_M-50_MiNNLO
                    - dyTo2Mu_M-100to200_MiNNLO
        DYVBF:
            processes:
                - dy_VBF_filter
            processes_per_year: {}

        TT:
            processes:
                - ttjets_dl
                - ttjets_sl
            processes_per_year: {}

        ST:
            processes:
                - st_tw_top
                - st_tw_antitop
                - st_t_top
                - st_t_antitop
            processes_per_year:
                2022preEE: {}
                2022postEE: {}
                2023: {}
                2023BPix: {}
                2024: {}

        EWK:
            processes:
                # - ewk_lljj_mll105_160_ptj0
                # - ewk_lljj_mll105_160_py_dipole
                # - ewk_lljj_mll50_mjj120
                # - ewk_lljj
                - ewk_mmjj_mll_105_160
            processes_per_year:
                2022preEE:
                    - ewk_mmjj_mll_105_160
                2022postEE:
                    - ewk_mmjj_mll_105_160
                2023:
                    - ewk_mmjj_mll_105_160
                2023BPix:
                    - ewk_mmjj_mll_105_160
                2018:
                    - ewk_zlljj
                    - ewk_lljj_mll50_mjj120
                2017:
                    - ewk_zlljj
                    - ewk_lljj_mll50_mjj120
                2016postVFP:
                    - ewk_zlljj
                    - ewk_lljj_mll50_mjj120
                2016preVFP:
                    - ewk_zlljj
                    - ewk_lljj_mll50_mjj120
        VV:
            processes:
                - ww_2l2nu
                - wz_3lnu
                - wz_2l2q
                - wz_1l1nu2q
                - zz_2l2nu
                - zz_2l2q
                - zz_4l
            processes_per_year:
                2018:
                    - ww_2l2nu
                    - wz_1l1nu2q
                    - wz_2l2q
                    - wz_3lnu
                    - zz
                2017:
                    - ww_2l2nu
                    - wz_1l1nu2q
                    - wz_2l2q
                    - wz_3lnu
                    - zz
                2016postVFP:
                    - ww_2l2nu
                    - wz_1l1nu2q
                    - wz_2l2q
                    - wz_3lnu
                    - zz
                2016preVFP:
                    - ww_2l2nu
                    - wz_1l1nu2q
                    - wz_2l2q
                    - wz_3lnu
                    - zz
        VVV:
            processes:
                - www
                - wwz
                - wzz
                - zzz
            processes_per_year:
                2022preEE: {}
                2022postEE: {}
                2023: {}
                2023BPix: {}

# --------------------------------------------------

signal:
    label: 1

    groups:
        VBF:
            processes:
                - vbf_powheg_dipole # pythia dipole
                # - vbf_powheg_herwig # herwig
                # - vbf_powhegPS # pythia 8
            processes_per_year:
                2025:
                    - vbf_powheg
                2023:
                    - vbf_powheg
                2023BPix:
                    - vbf_powheg
                2024:
                    - vbf_powheg
        GGH:
            processes:
                - ggh_powhegPS
            processes_per_year: {}

        # HIGGS:
        #     # Combined signal category (useful for inclusive plots / training)
        #     processes:
        #         - vbf_powheg_dipole
        #         - ggh_powhegPS
        #     processes_per_year:
        #         2023:
        #             - vbf_powheg
        #             - ggh_powhegPS
        #         2023BPix:
        #             - vbf_powheg
        #             - ggh_powhegPS
        #         2024:
        #             - vbf_powheg
        #             - ggh_powhegPS
