background:
    label: 0

    groups:
        DY:
            processes:
                # - dyTo2L_M-50_incl
                - dy_M-100To200_MiNNLO
                - dyTo2L_M-50_aMCatNLO
                - dy_VBF_filter
                # - dyTo2Mu_MLL_10To50
                # - dyTo2Mu_MLL_50To120
                # - dyTo2Mu_MLL_120To200
            processes_per_year:
                2024:
                    - dyTo2Mu_M-50_aMCatNLO
                # 2017:
                    # - dyTo2L_M-50_aMCatNLO

        TT:
            processes:
                - ttjets_dl
                - ttjets_sl
            processes_per_year: {}

        ST:
            processes:
                - st_tw_top
                - st_tw_antitop
                - st_t_top
                - st_t_antitop
            processes_per_year: {}

        EWK:
            processes:
                # - ewk_lljj_mll105_160_ptj0
                # - ewk_lljj_mll105_160_py_dipole
                - ewk_lljj_mll50_mjj120
                # - ewk_lljj
                - ewk_mmjj
                - ewk_zlljj
            processes_per_year:
                2022preEE:
                    - ewk_lljj
                2022postEE:
                    - ewk_lljj
                2023:
                    - ewk_lljj
                2023BPix:
                    - ewk_lljj
        VV:
            processes:
                - ww_2l2nu
                - wz_3lnu
                - wz_2l2q
                - wz_1l1nu2q
                - zz
            processes_per_year: {}

        # VVV:
        #     processes:
        #         - www
        #         - wwz
        #         - wzz
        #         - zzz
        #     processes_per_year: {}

# --------------------------------------------------

signal:
    label: 1

    groups:
        VBF:
            processes:
                - vbf_powheg_dipole # pythia dipole
                # - vbf_powheg_herwig # herwig
                # - vbf_powhegPS # pythia 8
            processes_per_year:
                2023:
                    - vbf_powheg
                2023BPix:
                    - vbf_powheg
                2024:
                    - vbf_powheg
        GGH:
            processes:
                - ggh_powhegPS
            processes_per_year: {}

        # HIGGS:
        #     # Combined signal category (useful for inclusive plots / training)
        #     processes:
        #         - vbf_powheg_dipole
        #         - ggh_powhegPS
        #     processes_per_year:
        #         2023:
        #             - vbf_powheg
        #             - ggh_powhegPS
        #         2023BPix:
        #             - vbf_powheg
        #             - ggh_powhegPS
        #         2024:
        #             - vbf_powheg
        #             - ggh_powhegPS
