year: 2018C
control_region: None # None, h-peak, h-sidebands, signal, z-peak
# directoryTag: Nov24_NanoCompare_DY_TRatioPlot_v4
directoryTag: Nov24_ParquetCompare_DY

input_paths_labels_data:
    # "v9": "/depot/cms/hmm/shar1172/OfficialNanoAODv9/Data/Run2018C/*.root"
    # "v9": "config/v9_files.txt"
    "v12": "/eos/purdue/store/user/rasharma/customNanoAOD_Gautschi_v2/UL2017/SingleMuon_Run2017C/*.root"
    "v15": "config/v15_files.txt"
    # "v12": "/eos/purdue/store/user/rasharma/customNanoAOD_Others/UL2018/SingleMuon_Run2018C/*.root"
    # "v9": "/depot/cms/hmm/shar1172/test/*.root"
    # "v12": "/depot/cms/hmm/shar1172/test2/*.root"
    # "v15": "root://xcache.cms.rcac.purdue.edu//store/data/Run2017C/SingleMuon/NANOAOD/UL2017_NanoAODv15-v1/2810000/57700297-283e-442c-8473-7e91a229ffc7.root"
    # "v15": "config/v15_files_test.txt"


input_paths_labels:
    "v9": "samples_txt_file/dy_M-50_aMCatNLO_v9.txt"
    "v12": "/eos/purdue/store/user/rasharma/Run2_CustomNanoAODv12/haddedv2/UL2017/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8_RunIISummer20UL17NanoAODv9/*.root"
    "v15": "samples_txt_file/dy_M-50_aMCatNLO_v15.txt"

input_parquet_paths_labels_data:
    "v12": "/depot/cms/users/yun79/hmm/copperheadV1clean/nanoV12_Nov24_2025/stage1_output/2017/f1_0/data_B/0/*.parquet"
    "v15": "/depot/cms/users/yun79/hmm/copperheadV1clean/nanoV15_Nov24_2025//stage1_output/2017/f1_0/data_B/0/*.parquet"

input_parquet_paths_labels:
    "v12": "/depot/cms/users/yun79/hmm/copperheadV1clean/nanoV12_Nov24_2025/stage1_output/2017/f1_0/dy_M-100To200_MiNNLO/0/*.parquet"
    "v15": "/depot/cms/users/yun79/hmm/copperheadV1clean/nanoV15_Nov24_2025//stage1_output/2017/f1_0/dy_M-100To200_MiNNLO/0/*.parquet"


plot_types:
    plot_1D: true

fields_to_load_data:
    - mu1_pt
    - mu1_ptErr
    # - ratio_pTErr_pt_mu1
    - mu1_eta
    - mu1_phi
    - mu2_pt
    - mu2_ptErr
    # - ratio_pTErr_pt_mu2
    - mu2_eta
    - mu2_phi
    - dimuon_pt
    - dimuon_eta
    - dimuon_phi
    - PV_npvs
    - PV_npvsGood
    - MET_pt
    - MET_phi
    - MET_sumEt
    - mu1_pt_over_mass
    - mu2_pt_over_mass
    - mu1_charge
    - mu2_charge
    - mu1_iso
    - mu2_iso
    - nmuons
    - dimuon_mass
    - dimuon_pt_log
    - dimuon_rapidity
    - dimuon_dEta
    - dimuon_dPhi
    - dimuon_dR
    - acoplanarity
    - dimuon_ebe_mass_res
    - dimuon_ebe_mass_res_rel
    - uncalibrated_dimuon_ebe_mass_res
    - dimuon_cos_theta_cs
    - dimuon_phi_cs
    - dimuon_cos_theta_eta
    - dimuon_phi_eta
    - mu1_pt_raw
    - mu2_pt_raw
    - mu1_pt_fsr
    - mu2_pt_fsr
    - year
    - run
    - luminosityBlock
    - fraction
    - jet1_default_pt_nominal
    - jet1_default_eta_nominal
    - jet2_default_pt_nominal
    - jet2_default_eta_nominal
    - jet1_pt_nominal
    - jet1_eta_nominal
    - jet1_rapidity_nominal
    - jet1_phi_nominal
    - jet1_pass_jetId_nominal
    - jet1_pass_puId_nominal
    - jet2_pt_nominal
    - jet2_eta_nominal
    - jet1_mass_nominal
    - jet2_mass_nominal
    - jet1_area_nominal
    - jet2_area_nominal
    - jet2_rapidity_nominal
    - jet2_phi_nominal
    - jet2_pass_jetId_nominal
    - jet2_pass_puId_nominal
    - jj_mass_nominal
    - jj_mass_log_nominal
    - jj_pt_nominal
    - jj_eta_nominal
    - jj_phi_nominal
    - jj_dEta_nominal
    - jj_dPhi_nominal
    - mmj1_dEta_nominal
    - mmj1_dPhi_nominal
    - mmj1_dR_nominal
    - mmj2_dEta_nominal
    - mmj2_dPhi_nominal
    - mmj2_dR_nominal
    - mmj_min_dEta_nominal
    - mmj_min_dPhi_nominal
    - mmjj_pt_nominal
    - mmjj_eta_nominal
    - mmjj_phi_nominal
    - mmjj_mass_nominal
    - rpt_nominal
    - pt_centrality_nominal
    - zeppenfeld_nominal
    - ll_zstar_log_nominal
    - njets_nominal
    - nsoftjets2_nominal
    - htsoft2_nominal
    - nsoftjets5_nominal
    - htsoft5_nominal
    - nBtagLoose_nominal
    - nBtagMedium_nominal
    - z_peak
    - h_sidebands
    - h_peak
    - wgt_nominal
    - separate_wgt_ones

fields_to_load:
    - mu1_pt
    - mu1_ptErr
    # - ratio_pTErr_pt_mu1
    - mu1_eta
    - mu1_phi
    - mu2_pt
    - mu2_ptErr
    # - ratio_pTErr_pt_mu2
    - mu2_eta
    - mu2_phi
    - dimuon_pt
    - dimuon_eta
    - dimuon_phi
    - PV_npvs
    - PV_npvsGood
    - MET_pt
    - MET_phi
    - MET_sumEt
    - mu1_pt_over_mass
    - mu2_pt_over_mass
    - mu1_charge
    - mu2_charge
    - mu1_iso
    - mu2_iso
    - nmuons
    - dimuon_mass
    - dimuon_pt_log
    - dimuon_rapidity
    - dimuon_dEta
    - dimuon_dPhi
    - dimuon_dR
    - acoplanarity
    - dimuon_ebe_mass_res
    - dimuon_ebe_mass_res_rel
    - uncalibrated_dimuon_ebe_mass_res
    - dimuon_cos_theta_cs
    - dimuon_phi_cs
    - dimuon_cos_theta_eta
    - dimuon_phi_eta
    - mu1_pt_raw
    - mu2_pt_raw
    - mu1_pt_fsr
    - mu2_pt_fsr
    - year
    - run
    - luminosityBlock
    - fraction
    - jet1_default_pt_nominal
    - jet1_default_eta_nominal
    - jet2_default_pt_nominal
    - jet2_default_eta_nominal
    - jet1_pt_nominal
    - jet1_eta_nominal
    - jet1_rapidity_nominal
    - jet1_phi_nominal
    - jet1_pass_jetId_nominal
    - jet1_pass_puId_nominal
    - jet2_pt_nominal
    - jet2_eta_nominal
    - jet1_mass_nominal
    - jet2_mass_nominal
    - jet1_area_nominal
    - jet2_area_nominal
    - jet2_rapidity_nominal
    - jet2_phi_nominal
    - jet2_pass_jetId_nominal
    - jet2_pass_puId_nominal
    - jj_mass_nominal
    - jj_mass_log_nominal
    - jj_pt_nominal
    - jj_eta_nominal
    - jj_phi_nominal
    - jj_dEta_nominal
    - jj_dPhi_nominal
    - mmj1_dEta_nominal
    - mmj1_dPhi_nominal
    - mmj1_dR_nominal
    - mmj2_dEta_nominal
    - mmj2_dPhi_nominal
    - mmj2_dR_nominal
    - mmj_min_dEta_nominal
    - mmj_min_dPhi_nominal
    - mmjj_pt_nominal
    - mmjj_eta_nominal
    - mmjj_phi_nominal
    - mmjj_mass_nominal
    - rpt_nominal
    - pt_centrality_nominal
    - zeppenfeld_nominal
    - ll_zstar_log_nominal
    - njets_nominal
    - nsoftjets2_nominal
    - htsoft2_nominal
    - nsoftjets5_nominal
    - htsoft5_nominal
    - nBtagLoose_nominal
    - nBtagMedium_nominal
    - z_peak
    - h_sidebands
    - h_peak
    - wgt_nominal
    - wgt_pu_wgt_down
    - wgt_THU_VBF_Mjj350_up
    - wgt_muIso_up
    - wgt_muIso_down
    - wgt_THU_VBF_Yield_up
    - wgt_LHERen_up
    - wgt_THU_VBF_Mjj700_up
    - wgt_l1prefiring_down
    - wgt_THU_VBF_JET01_down
    - wgt_THU_VBF_Mjj1500_up
    - wgt_pdf_2rms_up
    - wgt_THU_VBF_Mjj350_down
    - wgt_pdf_2rms_down
    - wgt_muTrig_down
    - wgt_pu_wgt_up
    - wgt_THU_VBF_Mjj120_up
    - wgt_THU_VBF_PTH25_up
    - wgt_l1prefiring_up
    - wgt_THU_VBF_PTH200_up
    - wgt_LHERen_down
    - wgt_muTrig_up
    - wgt_THU_VBF_Mjj1500_down
    - wgt_THU_VBF_Mjj60_down
    - wgt_THU_VBF_Mjj120_down
    - wgt_THU_VBF_Mjj1000_up
    - wgt_THU_VBF_Mjj1000_down
    - wgt_LHEFac_up
    - wgt_THU_VBF_Mjj60_up
    - wgt_muID_down
    - wgt_THU_VBF_JET01_up
    - wgt_THU_VBF_PTH25_down
    - wgt_LHEFac_down
    - wgt_muID_up
    - wgt_THU_VBF_Mjj700_down
    - wgt_THU_VBF_Yield_down
    - wgt_THU_VBF_PTH200_down
    - separate_wgt_genWeight
    - separate_wgt_genWeight_normalization
    - separate_wgt_xsec
    - separate_wgt_lumi
    - separate_wgt_pu_wgt
    - separate_wgt_l1prefiring
    - separate_wgt_muID
    - separate_wgt_muIso
    - separate_wgt_muTrig
    - separate_wgt_LHERen
    - separate_wgt_LHEFac
    - separate_wgt_THU_VBF_Yield
    - separate_wgt_THU_VBF_PTH200
    - separate_wgt_THU_VBF_Mjj60
    - separate_wgt_THU_VBF_Mjj120
    - separate_wgt_THU_VBF_Mjj350
    - separate_wgt_THU_VBF_Mjj700
    - separate_wgt_THU_VBF_Mjj1000
    - separate_wgt_THU_VBF_Mjj1500
    - separate_wgt_THU_VBF_PTH25
    - separate_wgt_THU_VBF_JET01
    - separate_wgt_pdf_2rms
    - separate_wgt_jetpuid_wgt
    - separate_wgt_zpt_wgt


NormalizeToUnity: True
LowerPadMode: "ratio"   # "diff" or "ratio"

variables:
    muon:
        - Muon_pt:
            - Range: [50, 20, 200]
            - Title: "Muon p_{T} [GeV]"
            - RatioPlot: [0.995, 1.005]

        # - Muon_bsConstrainedPt:
        #     - Range: [50, 20, 200]
        #     - Title: "BS Constrained Muon p_{T} [GeV]"
        #     - RatioPlot: [0.995, 1.005]

        - Muon_eta:
            - Range: [50, -4.7, 4.7]
            - Title: "Muon #eta"
            - RatioPlot: [0.98, 1.02]

        - Muon_phi:
            - Range: [50, -3.14, 3.14]
            - Title: "Muon #phi"
            - RatioPlot: [0.995, 1.005]


    electron:
        - Electron_pt:
            - Range: [50, 10, 200]
            - Title: "Electron p_{T} [GeV]"
            - RatioPlot: [0.9, 1.1]

        - Electron_eta:
            - Range: [50, -4.7, 4.7]
            - Title: "Electron #eta"
            - RatioPlot: [0.98, 1.02]

        - Electron_phi:
            - Range: [50, -3.14, 3.14]
            - Title: "Electron #phi"
            - RatioPlot: [0.995, 1.005]


    jet:
        - Jet_pt:
            - Range: [60, 0, 300]
            - Title: "Jet p_{T} [GeV]"
            - RatioPlot: [0.9, 1.1]

        - Jet_eta:
            - Range: [50, -4.7, 4.7]
            - Title: "Jet #eta"
            - RatioPlot: [0.95, 1.05]

        - Jet_phi:
            - Range: [50, -3.14, 3.14]
            - Title: "Jet #phi"
            - RatioPlot: [0.98, 1.02]

        - Jet_mass:
            - Range: [60, 0, 50]
            - Title: "Jet mass [GeV]"
            - RatioPlot: [0.9, 1.1]
