year: 2018C
control_region: None
directoryTag: Nov24_NanoCompare_DY_TRatioPlot_v4

input_paths_labels_data:
    # "v9": "/depot/cms/hmm/shar1172/OfficialNanoAODv9/Data/Run2018C/*.root"
    # "v9": "config/v9_files.txt"
    "v12": "/eos/purdue/store/user/rasharma/customNanoAOD_Gautschi_v2/UL2017/SingleMuon_Run2017C/*.root"
    "v15": "config/v15_files.txt"
    # "v12": "/eos/purdue/store/user/rasharma/customNanoAOD_Others/UL2018/SingleMuon_Run2018C/*.root"
    # "v9": "/depot/cms/hmm/shar1172/test/*.root"
    # "v12": "/depot/cms/hmm/shar1172/test2/*.root"
    # "v15": "root://xcache.cms.rcac.purdue.edu//store/data/Run2017C/SingleMuon/NANOAOD/UL2017_NanoAODv15-v1/2810000/57700297-283e-442c-8473-7e91a229ffc7.root"
    # "v15": "config/v15_files_test.txt"

input_paths_labels:
    "v9": "samples_txt_file/dy_M-50_aMCatNLO_v9.txt"
    "v12": "/eos/purdue/store/user/rasharma/Run2_CustomNanoAODv12/haddedv2/UL2017/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8_RunIISummer20UL17NanoAODv9/*.root"
    "v15": "samples_txt_file/dy_M-50_aMCatNLO_v15.txt"


plot_types:
    plot_1D: true

fields_to_load:
    - Muon_pt
    - Muon_eta
    - Muon_phi

NormalizeToUnity: True
LowerPadMode: "ratio"   # "diff" or "ratio"

variables:
    muon:
        - Muon_pt:
            - Range: [50, 20, 200]
            - Title: "Muon p_{T} [GeV]"
            - RatioPlot: [0.995, 1.005]

        # - Muon_bsConstrainedPt:
        #     - Range: [50, 20, 200]
        #     - Title: "BS Constrained Muon p_{T} [GeV]"
        #     - RatioPlot: [0.995, 1.005]

        - Muon_eta:
            - Range: [50, -4.7, 4.7]
            - Title: "Muon #eta"
            - RatioPlot: [0.98, 1.02]

        - Muon_phi:
            - Range: [50, -3.14, 3.14]
            - Title: "Muon #phi"
            - RatioPlot: [0.995, 1.005]


    electron:
        - Electron_pt:
            - Range: [50, 10, 200]
            - Title: "Electron p_{T} [GeV]"
            - RatioPlot: [0.9, 1.1]

        - Electron_eta:
            - Range: [50, -4.7, 4.7]
            - Title: "Electron #eta"
            - RatioPlot: [0.98, 1.02]

        - Electron_phi:
            - Range: [50, -3.14, 3.14]
            - Title: "Electron #phi"
            - RatioPlot: [0.995, 1.005]


    jet:
        - Jet_pt:
            - Range: [60, 0, 300]
            - Title: "Jet p_{T} [GeV]"
            - RatioPlot: [0.9, 1.1]

        - Jet_eta:
            - Range: [50, -4.7, 4.7]
            - Title: "Jet #eta"
            - RatioPlot: [0.95, 1.05]

        - Jet_phi:
            - Range: [50, -3.14, 3.14]
            - Title: "Jet #phi"
            - RatioPlot: [0.98, 1.02]

        - Jet_mass:
            - Range: [60, 0, 50]
            - Title: "Jet mass [GeV]"
            - RatioPlot: [0.9, 1.1]
