jet_pt_cut:
    2016preVFP: 25.0
    2016postVFP: 25.0
    "2017": 25.0
    "2018": 25.0
    2016_RERECO: 25.0
    "2017_RERECO": 25.0
    "2018_RERECO": 25.0
    "2022preEE": 25.0
    "2022postEE": 25.0
    "2023": 25.0
    "2023BPix": 25.0
    "2024": 25.0
jet_eta_cut:
    2016preVFP: 4.7
    2016postVFP: 4.7
    "2017": 4.7
    "2018": 4.7
    2016_RERECO: 4.7
    "2017_RERECO": 4.7
    "2018_RERECO": 4.7
    "2022preEE": 4.7
    "2022postEE": 4.7
    "2023": 4.7
    "2023BPix": 4.7
    "2024": 4.7
jet_id:
    # INFO: For 2016UL, we don't have loose ID, so make it just tight https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookNanoAOD#Jets
    # INFO: Use tight, tightPassLepVeto, or tightFailLepVeto
    2016preVFP: tight
    2016postVFP: tight
    "2017": tight
    "2018": tight
    2016_RERECO: loose
    "2017_RERECO": tight
    "2018_RERECO": tight
    "2022preEE": tight
    "2022postEE": tightPassLepVeto
    "2023": tight
    "2023BPix": tight
    "2024": tight
jet_id_json_files: # old method as of Dec 16 2024,
    2016preVFP: dummy
    2016postVFP: dummy
    "2017": dummy
    "2018": dummy
    2016_RERECO: dummy
    "2017_RERECO": dummy
    "2018_RERECO": dummy
    "2022preEE": /cvmfs/cms-griddata.cern.ch/cat/metadata/JME/Run3-22CDSep23-Summer22-NanoAODv12/2025-09-23/jetid.json.gz
    2022postEE: /cvmfs/cms-griddata.cern.ch/cat/metadata/JME/Run3-22EFGSep23-Summer22EE-NanoAODv12/2025-10-07/jetid.json.gz
    "2023": /cvmfs/cms-griddata.cern.ch/cat/metadata/JME/Run3-23CSep23-Summer23-NanoAODv12/2025-10-07/jetid.json.gz
    "2023BPix": /cvmfs/cms-griddata.cern.ch/cat/metadata/JME/Run3-23DSep23-Summer23BPix-NanoAODv12/2025-10-07/jetid.json.gz
    "2024": /cvmfs/cms-griddata.cern.ch/cat/metadata/JME/Run3-24CDEReprocessingFGHIPrompt-Summer24-NanoAODv15/2025-12-02/jetid.json.gz
jet_puid:
    2016preVFP: loose
    2016postVFP: loose
    "2017": loose
    "2018": loose
    2016_RERECO: loose
    "2017_RERECO": loose
    "2018_RERECO": loose
    "2022preEE": loose
    "2022postEE": loose
    "2023": loose
    "2023BPix": loose
    "2024": loose
min_dr_mu_jet:
    2016preVFP: 0.4
    2016postVFP: 0.4
    "2017": 0.4
    "2018": 0.4
    2016_RERECO: 0.4
    "2017_RERECO": 0.4
    "2018_RERECO": 0.4
    "2022preEE": 0.4
    "2022postEE": 0.4
    "2023": 0.4
    "2023BPix": 0.4
    "2024": 0.4
btag_loose_wp:
    2016preVFP: 0.2027 # DeepCSV
    2016postVFP: 0.1918 # DeepCSV
    "2017": 0.1355 # DeepCSV
    "2018": 0.1208 # DeepCSV central sources for UL https://btv-wiki.docs.cern.ch/ScaleFactors/UL2018/#ak4-b-tagging
    2016_RERECO: 0.2217 # DeepCSV central sources for RERECO https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation102X
    "2017_RERECO": 0.1522 # DeepCSV
    "2018_RERECO": 0.1241 # DeepCSV
    "2022preEE": 0.0583 # https://btv-wiki.docs.cern.ch/ScaleFactors/Run3Summer22/#ak4-b-tagging
    "2022postEE": 0.0583 # https://btv-wiki.docs.cern.ch/ScaleFactors/Run3Summer22/#ak4-b-tagging
    "2023": 0.0583 # https://btv-wiki.docs.cern.ch/ScaleFactors/Run3Summer22/#ak4-b-tagging
    "2023BPix": 0.0583 # https://btv-wiki.docs.cern.ch/ScaleFactors/Run3Summer22/#ak4-b-tagging
    "2024": 0.0246 # https://btv-wiki.docs.cern.ch/ScaleFactors/Run3Summer24/#ak4-b-tagging for UParTAK4
btag_medium_wp:
    2016preVFP: 0.6001 # DeepCSV
    2016postVFP: 0.5847 # DeepCSV
    "2017": 0.4506 # DeepCSV
    "2018": 0.4168 # DeepCSV
    2016_RERECO: 0.6321 # DeepCSV
    "2017_RERECO": 0.4941 # DeepCSV
    "2018_RERECO": 0.4184 # DeepCSV
    "2022preEE": 0.3086 # https://btv-wiki.docs.cern.ch/ScaleFactors/Run3Summer22/#ak4-b-tagging
    "2022postEE": 0.3086 # https://btv-wiki.docs.cern.ch/ScaleFactors/Run3Summer22/#ak4-b-tagging
    "2023": 0.3086 # https://btv-wiki.docs.cern.ch/ScaleFactors/Run3Summer22/#ak4-b-tagging
    "2023BPix": 0.3086 # https://btv-wiki.docs.cern.ch/ScaleFactors/Run3Summer22/#ak4-b-tagging
    "2024": 0.1272 # https://btv-wiki.docs.cern.ch/ScaleFactors/Run3Summer24/#ak4-b-tagging for UParTAK4
softjet_dr2:
    2016preVFP: 0.16
    2016postVFP: 0.16
    "2017": 0.16
    "2018": 0.16
    2016_RERECO: 0.16
    "2017_RERECO": 0.16
    "2018_RERECO": 0.16
    "2022preEE": 0.16
    "2022postEE": 0.16
    "2023": 0.16
    "2023BPix": 0.16
    "2024": 0.16
HemVeto_ratio: # ratio of HemVeto applicable run / total nevents for 2018UL
    2016preVFP: 0.0
    2016postVFP: 0.0
    "2017": 0.0
    "2018": 0.2032434833227702
    2016_RERECO: 0.0
    "2017_RERECO": 0.0
    "2018_RERECO": 0.0
    "2022preEE": 0.0
    "2022postEE": 0.0
    "2023": 0.0
    "2023BPix": 0.0
    "2024": 0.0
jet_veto_maps:
    2016preVFP: /cvmfs/cms-griddata.cern.ch/cat/metadata/JME/Run2-2016preVFP-UL-NanoAODv9/2025-04-11/jetvetomaps.json.gz
    2016postVFP: /cvmfs/cms-griddata.cern.ch/cat/metadata/JME/Run2-2016postVFP-UL-NanoAODv9/2025-04-11/jetvetomaps.json.gz
    "2017": /cvmfs/cms-griddata.cern.ch/cat/metadata/JME/Run2-2017-UL-NanoAODv9/2025-04-11/jetvetomaps.json.gz
    "2018": /cvmfs/cms-griddata.cern.ch/cat/metadata/JME/Run2-2018-UL-NanoAODv9/2025-04-11/jetvetomaps.json.gz
    2022preEE: /cvmfs/cms-griddata.cern.ch/cat/metadata/JME/Run3-22CDSep23-Summer22-NanoAODv12/2025-09-23/jetvetomaps.json.gz
    2022postEE: /cvmfs/cms-griddata.cern.ch/cat/metadata/JME/Run3-22EFGSep23-Summer22EE-NanoAODv12/2025-10-07/jetvetomaps.json.gz
    "2023": /cvmfs/cms-griddata.cern.ch/cat/metadata/JME/Run3-23CSep23-Summer23-NanoAODv12/2025-10-07/jetvetomaps.json.gz
    2023BPix: /cvmfs/cms-griddata.cern.ch/cat/metadata/JME/Run3-23DSep23-Summer23BPix-NanoAODv12/2025-10-07/jetvetomaps.json.gz
    "2024": /cvmfs/cms-griddata.cern.ch/cat/metadata/JME/Run3-24CDEReprocessingFGHIPrompt-Summer24-NanoAODv15/2025-07-17/jetvetomaps.json.gz
jet_veto_maps_tag:
    "2016preVFP": None
    "2016postVFP": None
    "2017": None
    "2018": None
    "2022preEE": Summer22_23Sep2023_RunCD_V1
    "2022postEE": Summer22EE_23Sep2023_RunEFG_V1
    "2023": Summer23Prompt23_RunC_V1
    "2023BPix": Summer23BPixPrompt23_RunD_V1
    "2024": Summer24Prompt24_RunBCDEFGHI_V1
