# Official path: /cvmfs/cms-griddata.cern.ch/cat/metadata/LUM/Run3-22CDSep23-Summer22-NanoAODv12/2024-01-31/puWeights.json.gz
# corresponding local path: data/cat/metadata/LUM/Run3-22CDSep23-Summer22-NanoAODv12/2024-01-31/puWeights.json.gz

nnlops_file:
    2016preVFP: data/NNLOPS_reweight.root
    2016postVFP: data/NNLOPS_reweight.root
    "2017": data/NNLOPS_reweight.root
    "2018": data/NNLOPS_reweight.root
    2016_RERECO: data/NNLOPS_reweight.root
    "2017_RERECO": data/NNLOPS_reweight.root
    "2018_RERECO": data/NNLOPS_reweight.root
    "2022preEE": data/NNLOPS_reweight.root
    2022postEE: data/NNLOPS_reweight.root
    "2023": data/NNLOPS_reweight.root
    "2023BPix": data/NNLOPS_reweight.root
    "2024": data/NNLOPS_reweight.root
btag_sf_json:
    2016preVFP: /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2016preVFP_UL/btagging.json.gz
    2016postVFP: /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2016postVFP_UL/btagging.json.gz
    "2017": /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2017_UL/btagging.json.gz
    "2018": /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2018_UL/btagging.json.gz
    2016_RERECO: /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2016preVFP_UL/btagging.json.gz
    "2017_RERECO": /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2017_UL/btagging.json.gz
    "2018_RERECO": /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2018_UL/btagging.json.gz
    "2022preEE": /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2022_Summer22EE/btagging.json.gz
    2022postEE: /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2022_Summer22EE/btagging.json.gz
    "2023": /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2023_Summer23/btagging.json.gz
    2023BPix: /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2023_Summer23BPix/btagging.json.gz
    "2024": /cvmfs/cms-griddata.cern.ch/cat/metadata/BTV/Run3-24CDEReprocessingFGHIPrompt-Summer24-NanoAODv15/2025-08-19/btagging.json.gz
btag_sf_csv:
    2016preVFP: data/btag/DeepCSV_2016LegacySF_V1.csv
    2016postVFP: data/btag/DeepCSV_2016LegacySF_V1.csv
    "2017": data/btag/DeepCSV_106XUL17SF.csv
    "2018": data/btag/DeepCSV_106XUL18SF.csv
    2016_RERECO: data/btag/DeepCSV_2016LegacySF_V1.csv
    "2017_RERECO": data/btag/DeepCSV_94XSF_V5_B_F.csv
    "2018_RERECO": data/btag/DeepCSV_102XSF_V1.csv
    "2022preEE": data/btag/DeepCSV_106XUL18SF.csv # FIXME: Update SF
    2022postEE: data/btag/DeepCSV_106XUL18SF.csv # FIXME: Update SF
    "2023": data/btag/DeepCSV_106XUL18SF.csv # FIXME: Update SF
    "2023BPix": data/btag/DeepCSV_106XUL18SF.csv # FIXME: Update SF
    "2024": data/btag/DeepCSV_106XUL18SF.csv # FIXME: Update SF
pu_file_data:
    2016preVFP: data/pileup/puData2016_UL_withVar.root
    2016postVFP: data/pileup/puData2016_UL_withVar.root
    "2017": data/pileup/puData2017_UL_withVar.root
    "2018": data/pileup/puData2018_UL_withVar.root
    2016_RERECO: data/pileup/PileupData_GoldenJSON_Full2016.root
    "2017_RERECO": data/pileup/puData2017_withVar.root
    "2018_RERECO": data/pileup/puData2018_withVar.root
    "2022preEE": dummy_only_pu_file_mc_is_needed
    2022postEE: dummy_only_pu_file_mc_is_needed
    "2023": dummy_only_pu_file_mc_is_needed # FIXME
    "2023BPix": dummy_only_pu_file_mc_is_needed # FIXME
    "2024": dummy_only_pu_file_mc_is_needed # FIXME
pu_file_mc: # source https://github.com/cms-sw/cmssw/blob/CMSSW_10_6_X/SimGeneral/MixingModule/python/mix_2018_25ns_UltraLegacy_PoissonOOTPU_cfi.py
    2016preVFP: data/pileup/mix_2016_25ns_UltraLegacy_PoissonOOTPU_cfi.yaml
    2016postVFP: data/pileup/mix_2016_25ns_UltraLegacy_PoissonOOTPU_cfi.yaml
    "2017": data/pileup/mix_2017_25ns_UltraLegacy_PoissonOOTPU_cfi.yaml
    "2018": data/pileup/mix_2018_25ns_UltraLegacy_PoissonOOTPU_cfi.yaml
    # Reference: https://cms-analysis-corrections.docs.cern.ch/corrections/LUM/Run3-23DSep23-Summer23BPix-NanoAODv12/latest/
    # 2016preVFP: data/cat/metadata/LUM/Run2-2016preVFP-UL-NanoAODv9/2021-09-10/puWeights.json.gz
    # 2016postVFP: data/cat/metadata/LUM/Run2-2016postVFP-UL-NanoAODv9/2021-09-10/puWeights.json.gz
    # "2017": data/cat/metadata/LUM/Run2-2017-UL-NanoAODv9/2021-09-10/puWeights.json.gz
    # "2018": data/cat/metadata/LUM/Run2-2018-UL-NanoAODv9/2021-09-10/puWeights.json.gz
    2016_RERECO: data/pileup/pileup_profile_Summer16.root
    "2017_RERECO": data/pileup/mcPileup2017.root
    "2018_RERECO": data/pileup/mcPileup2018.root
    "2022preEE": data/cat/metadata/LUM/Run3-22CDSep23-Summer22-NanoAODv12/2024-01-31/puWeights.json.gz
    2022postEE: data/cat/metadata/LUM/Run3-22EFGSep23-Summer22EE-NanoAODv12/2024-01-31/puWeights.json.gz
    "2023": data/cat/metadata/LUM/Run3-23CSep23-Summer23-NanoAODv12/2024-01-31/puWeights.json.gz
    2023BPix: data/cat/metadata/LUM/Run3-23DSep23-Summer23BPix-NanoAODv12/2024-01-31/puWeights.json.gz
    "2024": data/cat/metadata/LUM/Run3-24CDEReprocessingFGHIPrompt-Summer24-NanoAODv15/2025-12-02/puWeights_BCDEFGHI.json.gz
muSFFileList:
    2016preVFP:
        - id:
              - data/muon_sf/year2016/MuonSF_Run2016_UL_HIPM_ID.root
              - NUM_MediumID_DEN_TrackerMuons_abseta_pt
          iso:
              - data/muon_sf/year2016/MuonSF_Run2016_UL_HIPM_ISO.root
              - NUM_TightRelIso_DEN_MediumID_abseta_pt
          trig:
              - data/muon_sf/mu2016/EfficienciesStudies_2016_trigger_EfficienciesAndSF_RunBtoF.root
              - IsoMu24_OR_IsoTkMu24_PtEtaBins/efficienciesDATA/abseta_pt_DATA
              - IsoMu24_OR_IsoTkMu24_PtEtaBins/efficienciesMC/abseta_pt_MC
          scale: 1.0
    2016postVFP:
        - id:
              - data/muon_sf/year2016/MuonSF_Run2016_UL_ID.root
              - NUM_MediumID_DEN_TrackerMuons_abseta_pt
          iso:
              - data/muon_sf/year2016/MuonSF_Run2016_UL_ISO.root
              - NUM_TightRelIso_DEN_MediumID_abseta_pt
          trig:
              - data/muon_sf/mu2016/EfficienciesStudies_2016_trigger_EfficienciesAndSF_RunGtoH.root
              - IsoMu24_OR_IsoTkMu24_PtEtaBins/efficienciesDATA/abseta_pt_DATA
              - IsoMu24_OR_IsoTkMu24_PtEtaBins/efficienciesMC/abseta_pt_MC
          scale: 1.0
    "2017":
        - id:
              - data/muon_sf/year2017/MuonSF_Run2017_UL_ID.root
              - NUM_MediumID_DEN_TrackerMuons_abseta_pt
          iso:
              - data/muon_sf/year2017/MuonSF_Run2017_UL_ISO.root
              - NUM_TightRelIso_DEN_MediumID_abseta_pt
          trig:
              - data/muon_sf/mu2017/EfficienciesAndSF_RunBtoF_Nov17Nov2017.root
              - IsoMu27_PtEtaBins/efficienciesDATA/abseta_pt_DATA
              - IsoMu27_PtEtaBins/efficienciesMC/abseta_pt_MC
          scale: 1.0
    "2018":
        - id:
              - data/muon_sf/year2018/MuonSF_Run2018_UL_ID.root # UL
              - NUM_MediumID_DEN_TrackerMuons_abseta_pt # UL
          # - data/muon_sf/year2018/RunABCD_SF_ID.root # rereco
          # - NUM_MediumID_DEN_genTracks_pt_abseta # rereco
          iso:
              - data/muon_sf/year2018/MuonSF_Run2018_UL_ISO.root # UL
              - NUM_TightRelIso_DEN_MediumID_abseta_pt # UL
          # - data/muon_sf/year2018/RunABCD_SF_ISO.root # rereco
          # - NUM_TightRelIso_DEN_MediumID_pt_abseta # rereco
          trig:
              - data/muon_sf/mu2018/EfficienciesStudies_2018_trigger_EfficienciesAndSF_2018Data_BeforeMuonHLTUpdate.root
              - IsoMu24_PtEtaBins/efficienciesDATA/abseta_pt_DATA
              - IsoMu24_PtEtaBins/efficienciesMC/abseta_pt_MC
          scale: 0.14981586876464678 # 8.95 / 59.74
        - id:
              - data/muon_sf/year2018/MuonSF_Run2018_UL_ID.root # UL
              - NUM_MediumID_DEN_TrackerMuons_abseta_pt # UL
          # - data/muon_sf/year2018/RunABCD_SF_ID.root # rereco
          # - NUM_MediumID_DEN_genTracks_pt_abseta # rereco
          iso:
              - data/muon_sf/year2018/MuonSF_Run2018_UL_ISO.root # UL
              - NUM_TightRelIso_DEN_MediumID_abseta_pt # UL
          # - data/muon_sf/year2018/RunABCD_SF_ISO.root # rereco
          # - NUM_TightRelIso_DEN_MediumID_pt_abseta # rereco
          trig:
              - data/muon_sf/mu2018/EfficienciesStudies_2018_trigger_EfficienciesAndSF_2018Data_AfterMuonHLTUpdate.root
              - IsoMu24_PtEtaBins/efficienciesDATA/abseta_pt_DATA
              - IsoMu24_PtEtaBins/efficienciesMC/abseta_pt_MC
          scale: 0.8501841312353532 # 50.79 / 59.74
    2016_RERECO:
        - id:
              - data/muon_sf/year2016/RunBCDEF_SF_ID.root
              - NUM_MediumID_DEN_genTracks_eta_pt
          iso:
              - data/muon_sf/year2016/RunBCDEF_SF_ISO.root
              - NUM_TightRelIso_DEN_MediumID_eta_pt
          trig:
              - data/muon_sf/mu2016/EfficienciesStudies_2016_trigger_EfficienciesAndSF_RunBtoF.root
              - IsoMu24_OR_IsoTkMu24_PtEtaBins/efficienciesDATA/abseta_pt_DATA
              - IsoMu24_OR_IsoTkMu24_PtEtaBins/efficienciesMC/abseta_pt_MC
          scale: 0.552197802
        - id:
              - data/muon_sf/year2016/RunGH_SF_ID.root
              - NUM_MediumID_DEN_genTracks_eta_pt
          iso:
              - data/muon_sf/year2016/RunGH_SF_ISO.root
              - NUM_TightRelIso_DEN_MediumID_eta_pt
          trig:
              - data/muon_sf/mu2016/EfficienciesStudies_2016_trigger_EfficienciesAndSF_RunGtoH.root
              - IsoMu24_OR_IsoTkMu24_PtEtaBins/efficienciesDATA/abseta_pt_DATA
              - IsoMu24_OR_IsoTkMu24_PtEtaBins/efficienciesMC/abseta_pt_MC
          scale: 0.447802198
    "2017_RERECO":
        - id:
              - data/muon_sf/year2017/RunBCDEF_SF_ID.root
              - NUM_MediumID_DEN_genTracks_pt_abseta
          iso:
              - data/muon_sf/year2017/RunBCDEF_SF_ISO.root
              - NUM_TightRelIso_DEN_MediumID_pt_abseta
          trig:
              - data/muon_sf/mu2017/EfficienciesAndSF_RunBtoF_Nov17Nov2017.root
              - IsoMu27_PtEtaBins/efficienciesDATA/abseta_pt_DATA
              - IsoMu27_PtEtaBins/efficienciesMC/abseta_pt_MC
          scale: 1.0
    "2018_RERECO":
        - id:
              - data/muon_sf/year2018/RunABCD_SF_ID.root
              - NUM_MediumID_DEN_genTracks_pt_abseta
          iso:
              - data/muon_sf/year2018/RunABCD_SF_ISO.root
              - NUM_TightRelIso_DEN_MediumID_pt_abseta
          trig:
              - data/muon_sf/mu2018/EfficienciesStudies_2018_trigger_EfficienciesAndSF_2018Data_BeforeMuonHLTUpdate.root
              - IsoMu24_PtEtaBins/efficienciesDATA/abseta_pt_DATA
              - IsoMu24_PtEtaBins/efficienciesMC/abseta_pt_MC
          scale: 0.149815869
    "2022preEE":
        - json_file: /cvmfs/cms-griddata.cern.ch/cat/metadata/MUO/Run3-22CDSep23-Summer22-NanoAODv12/2025-08-14/muon_Z.json.gz
        - id: NUM_TightID_DEN_TrackerMuons
        - iso: NUM_LoosePFIso_DEN_TightID
        - trig: NUM_IsoMu24_DEN_CutBasedIdTight_and_PFIsoTight
    2022postEE:
        - json_file: /cvmfs/cms-griddata.cern.ch/cat/metadata/MUO/Run3-22EFGSep23-Summer22EE-NanoAODv12/2025-08-14/muon_Z.json.gz
        - id: NUM_TightID_DEN_TrackerMuons
        - iso: NUM_LoosePFIso_DEN_TightID
        - trig: NUM_IsoMu24_DEN_CutBasedIdTight_and_PFIsoTight
    "2023":
        - json_file: /cvmfs/cms-griddata.cern.ch/cat/metadata/MUO/Run3-23CSep23-Summer23-NanoAODv12/2025-08-14/muon_Z.json.gz
        - id: NUM_TightID_DEN_TrackerMuons
        - iso: NUM_LoosePFIso_DEN_TightID
        - trig: NUM_IsoMu24_DEN_CutBasedIdTight_and_PFIsoTight
    "2023BPix":
        - json_file: /cvmfs/cms-griddata.cern.ch/cat/metadata/MUO/Run3-23DSep23-Summer23BPix-NanoAODv12/2025-08-14/muon_Z.json.gz
        - id: NUM_TightID_DEN_TrackerMuons
        - iso: NUM_LoosePFIso_DEN_TightID
        - trig: NUM_IsoMu24_DEN_CutBasedIdTight_and_PFIsoTight
    "2024":
        json_file: /cvmfs/cms-griddata.cern.ch/cat/metadata/MUO/Run3-24CDEReprocessingFGHIPrompt-Summer24-NanoAODv15/2025-11-27/muon_Z.json.gz
        id: NUM_TightID_DEN_TrackerMuons
        iso: NUM_LoosePFIso_DEN_TightID
        trig: NUM_IsoMu24_DEN_CutBasedIdTight_and_PFIsoTight
new_zpt_weights_file_aMCatNLO:
    "2018": data/zpt_rewgt/zpt_rewgt_params_aMCatNLO.yaml
    "2017": data/zpt_rewgt/zpt_rewgt_params_aMCatNLO.yaml
    "2016preVFP": data/zpt_rewgt/zpt_rewgt_params_aMCatNLO.yaml
    "2016postVFP": data/zpt_rewgt/zpt_rewgt_params_aMCatNLO.yaml
    "2022preEE": data/zpt_rewgt/zpt_rewgt_params_INCamcatnloFXFX.yaml
    "2022postEE": data/zpt_rewgt/zpt_rewgt_params_INCamcatnloFXFX.yaml
    "2023": data/zpt_rewgt/zpt_rewgt_params_INCamcatnloFXFX.yaml
    "2023BPix": data/zpt_rewgt/zpt_rewgt_params_INCamcatnloFXFX.yaml
    "2024": data/zpt_rewgt/zpt_rewgt_params_INCamcatnloFXFX.yaml
new_zpt_weights_file_MiNNLO:
    2016preVFP: data/zpt_rewgt/zpt_rewgt_params_minnlo.yaml
    2016postVFP: data/zpt_rewgt/zpt_rewgt_params_minnlo.yaml
    "2017": data/zpt_rewgt/zpt_rewgt_params_minnlo.yaml
    "2018": data/zpt_rewgt/zpt_rewgt_params_minnlo.yaml
    2016_RERECO: data/zpt_rewgt/zpt_rewgt_params.yaml
    "2017_RERECO": data/zpt_rewgt/zpt_rewgt_params.yaml
    "2018_RERECO": data/zpt_rewgt/zpt_rewgt_params.yaml
    "2022preEE": None
    2022postEE: None
    "2023": None
    "2023BPix": None
    "2024": None
zpt_dnn_models_aMCatNLO:
    "2018": dummy
    "2017": dummy
    "2016preVFP": dummy
    "2016postVFP": dummy
    "2022preEE": dummy
    "2022postEE": dummy
    "2023": dummy
    "2023BPix": dummy
    "2024":
        0j: dummy
        1j: dummy
        2j: dummy
jetpuid_sf_file: # old method as of Dec 16 2024,
    2016preVFP: data/PUID_106XTraining_ULRun2_EffSFandUncties_v1.root
    2016postVFP: data/PUID_106XTraining_ULRun2_EffSFandUncties_v1.root
    "2017": data/PUID_106XTraining_ULRun2_EffSFandUncties_v1.root
    "2018": data/PUID_106XTraining_ULRun2_EffSFandUncties_v1.root
    2016_RERECO: data/PUIDMaps.root
    "2017_RERECO": data/PUIDMaps.root
    "2018_RERECO": data/PUIDMaps.root
    "2022preEE": data/cat/metadata/JME/Run3-22CDSep23-Summer22-NanoAODv12/2025-09-23/jetid.json.gz
    2022postEE: /cvmfs/cms-griddata.cern.ch/cat/metadata/JME/Run3-22EFGSep23-Summer22EE-NanoAODv12/2025-10-07/jetid.json.gz
    "2023": /cvmfs/cms-griddata.cern.ch/cat/metadata/JME/Run3-23CSep23-Summer23-NanoAODv12/2025-10-07/jetid.json.gz
    "2023BPix": /cvmfs/cms-griddata.cern.ch/cat/metadata/JME/Run3-23DSep23-Summer23BPix-NanoAODv12/2025-10-07/jetid.json.gz
    "2024": /cvmfs/cms-griddata.cern.ch/cat/metadata/JME/Run3-24CDEReprocessingFGHIPrompt-Summer24-NanoAODv15/2025-12-02/jetid.json.gz
jmar_sf_file:
    2016preVFP: /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/JME/2016preVFP_UL/jmar.json.gz
    2016postVFP: /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/JME/2016postVFP_UL/jmar.json.gz
    "2017": /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/JME/2017_UL/jmar.json.gz # while this is listed, we use jetpuid_sf_file for 2017 (old method)
    "2018": /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/JME/2018_UL/jmar.json.gz
    # 2016preVFP: data/POG/JME/2016preVFP_UL/jmar.json.gz
    # 2016postVFP: data/POG/JME/2016postVFP_UL/jmar.json.gz
    # '2017': data/POG/JME/2017_UL/jmar.json.gz # while this is listed, we use jetpuid_sf_file for 2017 (old method)
    # '2018': data/POG/JME/2018_UL/jmar.json.gz
    2016_RERECO: dummy
    "2017_RERECO": dummy
    "2018_RERECO": dummy
    "2022preEE": dummy
    2022postEE: dummy
    "2023": dummy
    "2023BPix": dummy
    "2024": dummy
