switches:
    save_full_muon_detail:
        '2016preVFP': false
        '2016postVFP': false
        '2017': false
        '2018': false
        '2022preEE': false
        '2022postEE': false
        "2023": false
        "2023BPix": false
        "2024": false
    do_additional_vars:
        '2016preVFP': false
        '2016postVFP': false
        '2017': false
        '2018': false
        '2022preEE': false
        '2022postEE': false
        "2023": false
        "2023BPix": false
        "2024": false
    save_all_weight_vars:
        '2016preVFP': false
        '2016postVFP': false
        '2017': false
        '2018': false
        '2022preEE': false
        '2022postEE': false
        "2023": false
        "2023BPix": false
        "2024": false
    do_save_partial_weights:
        '2016preVFP': false
        '2016postVFP': false
        '2017': false
        '2018': false
        '2022preEE': false
        '2022postEE': false
        "2023": false
        "2023BPix": false
        "2024": false
    do_additional_jet_vars:
        '2016preVFP': false
        '2016postVFP': false
        '2017': false
        '2018': false
        '2022preEE': false
        '2022postEE': false
        "2023": false
        "2023BPix": false
        "2024": false
    do_getFatJet_vars:
        '2016preVFP': false
        '2016postVFP': false
        '2017': false
        '2018': false
        '2022preEE': false
        '2022postEE': false
        "2023": false
        "2023BPix": false
        "2024": false
    do_nnlops:
        '2016preVFP': true
        '2016postVFP': true
        '2017': true
        '2018': true
        '2022preEE': true
        '2022postEE': true
        "2023": true
        "2023BPix": true
        "2024": true
    do_pdf:
        '2016preVFP': true
        '2016postVFP': true
        '2017': true
        '2018': true
        '2022preEE': true
        '2022postEE': true
        "2023": true
        "2023BPix": true
        "2024": true
    do_THU:
        '2016preVFP': true
        '2016postVFP': true
        '2017': true
        '2018': true
        '2022preEE': true
        '2022postEE': true
        "2023": true
        "2023BPix": true
        "2024": true
    do_trigger_match:
        '2016preVFP': true
        '2016postVFP': true
        '2017': true
        '2018': true
        '2022preEE': true
        '2022postEE': true
        "2023": true
        "2023BPix": true
        "2024": true
    do_pu_wgt:
        '2016preVFP': true
        '2016postVFP': true
        '2017': true
        '2018': true
        '2022preEE': true
        '2022postEE': true
        "2023": true
        "2023BPix": true
        "2024": true
    do_roccor:
        '2016preVFP': true
        '2016postVFP': true
        '2017': true
        '2018': true
        '2022preEE': true
        '2022postEE': true
        "2023": true
        "2023BPix": true
        "2024": true
    do_fsr:
        '2016preVFP': true
        '2016postVFP': true
        '2017': true
        '2018': true
        '2022preEE': true
        '2022postEE': true
        "2023": true
        "2023BPix": true
        "2024": true
    do_geofit:
        '2016preVFP': false
        '2016postVFP': false
        '2017': false
        '2018': false
        '2022preEE': false
        '2022postEE': false
        "2023": false
        "2023BPix": false
        "2024": false
    do_beamConstraint:
        '2016preVFP': true
        '2016postVFP': true
        '2017': true
        '2018': true
        '2022preEE': true
        '2022postEE': true
        "2023": true
        "2023BPix": true
        "2024": true
    do_l1prefiring_wgts:
        2016preVFP: true
        2016postVFP: true
        "2017": true
        "2018": false
        2016_RERECO: true
        "2017_RERECO": true
        "2018_RERECO": false
        2022preEE: false
        2022postEE: false
        "2023": false
        "2023BPix": false
        "2024": false
    do_remove_dy_M100to200: # Remove 100 to 200 mll region from inclusive DY.
        '2016preVFP': false
        '2016postVFP': false
        '2017': false
        '2018': false
        '2022preEE': false
        '2022postEE': false
        "2023": false
        "2023BPix": false
        "2024": false
    do_zpt:
        '2016preVFP': true
        '2016postVFP': true
        '2017': true
        '2018': true
        '2022preEE': true
        '2022postEE': true
        "2023": true
        "2023BPix": true
        "2024": true
    apply_jet_PUID_wgt:
        '2016preVFP': false
        '2016postVFP': false
        '2017': false
        '2018': false
        '2022preEE': false
        '2022postEE': false
        "2023": false
        "2023BPix": false
        "2024": false
    do_HemVeto:
        '2016preVFP': false
        '2016postVFP': false
        '2017': false
        '2018': true # For nanoAODv15, we don't have the proper ratio yet
        '2022preEE': false
        '2022postEE': false
        "2023": false
        "2023BPix": false
        "2024": false
    do_HemVetoStudy: # this should be true for obtaining the HemVeto_ratio value below. See documenation
        '2016preVFP': false
        '2016postVFP': false
        '2017': false
        '2018': false # this should be false in normal copperheadV2 run
        '2022preEE': false
        '2022postEE': false
        "2023": false
        "2023BPix": false
        "2024": false
    do_jet_veto_maps_filterEvents: # remove the events
        '2016preVFP': false
        '2016postVFP': false
        '2017': false
        '2018': false
        '2022preEE': false
        '2022postEE': false
        "2023": false
        "2023BPix": false
        "2024": false
    do_jet_veto_maps_filterJets: # remove the jets not events
        '2016preVFP': false
        '2016postVFP': false
        '2017': false
        '2018': false
        '2022preEE': true
        '2022postEE': true
        "2023": true
        "2023BPix": true
        "2024": true
    do_jet_horn_ptcut: # For run-3 where the JME recommendation is to add pT > 50 GeV cut in the horn region
        # Currently, updated the pT to 30 GeV
        '2016preVFP': false
        '2016postVFP': false
        '2017': false
        '2018': false
        '2022preEE': 30.0
        '2022postEE': 30.0
        "2023": 30.0
        "2023BPix": 30.0
        "2024": 30.0
    do_jet_HE_nConstCut: # For run-3 we scanned and noted that for nconstituents <= 3 its mostly fake jets.
        '2016preVFP': false
        '2016postVFP': false
        '2017': false
        '2018': false
        '2022preEE': false
        '2022postEE': false
        "2023": false
        "2023BPix": false
        "2024": false
    add_pt_cut_for_HE_HF_jets:
        '2016preVFP': false
        '2016postVFP': false
        '2017': false
        '2018': false
        '2022preEE': false
        '2022postEE': false
        "2023": false
        "2023BPix": false
        "2024": false
    add_asymmetric_pt_cut_for_HE_HF_jets:
        '2016preVFP': false
        '2016postVFP': false
        '2017': false
        '2018': false
        '2022preEE': false # [35.0, 30.0] or false
        '2022postEE': false # [35.0, 30.0] or false
        "2023": false # [35.0, 30.0] or false
        "2023BPix": false # [35.0, 30.0] or false
        "2024": false # [35.0, 30.0] or false
    do_jet_horn_puid: # For run-2 samples where we added strict PUID cut for the horn region
        '2016preVFP': false # For nanoAODv12, do_jet_horn_puid should be true
        '2016postVFP': false # For nanoAODv12, do_jet_horn_puid should be true
        '2017': false # For nanoAODv12, do_jet_horn_puid should be true
        '2018': false # For nanoAODv12, do_jet_horn_puid should be true
        '2022preEE': false
        '2022postEE': false
        "2023": false
        "2023BPix": false
        "2024": false
    do_jec:
        '2016preVFP': true
        '2016postVFP': true
        '2017': true
        '2018': true
        '2022preEE': true
        '2022postEE': true
        "2023": true
        "2023BPix": true
        "2024": true
    jer_strat: # JER strat. -1 is to not apply jer, 0 is JME default, 1 is jer strat1, 2 is jer strat2, 3 is jer 1n2Revised.
        # ---------------------------------------
        # jer strat description
        # ---------------------------------------
        # -1 : apply no jer smearing.
        # 0 : default hybrid jer. Apply scaling method for real jets. Apply stochastic method for fake jets (source: https://twiki.cern.ch/twiki/bin/view/CMS/JetResolution)
        # 1 : jer strat 1 from Brenda VBF SUSY. Apply scaling method for real jets. Apply stochastic method for fake jets if pT > 50. For fake jets with pT < 50 and passing tight PU Id, apply stochastic method. For fake jets with pT < 50 and failing tight PU Id, apply no jer smearing.
        # 2 : jer strat 2 from Brenda VBF SUSY. Apply scaling method for real jets. Apply stochastic method for fake jets except fake jets with pT <= 50 and abseta > 2.5. For fake jets with pT <= 50 and abseta > 2.5, apply no jer smearing.
        # 3 : our custom Run2 jer smearinig method for CHS jets. Source: https://indico.cern.ch/event/1499935/#175-update-from-purdue, slide 19
        '2016preVFP': 0 # For nanoAODv12, jer_strat should be 3
        '2016postVFP': 0 # For nanoAODv12, jer_strat should be 3
        '2017': 0 # For nanoAODv12, jer_strat should be 3
        '2018': 0 # For nanoAODv12, jer_strat should be 3
        '2022preEE': -1
        '2022postEE': -1
        "2023": -1
        "2023BPix": -1
        "2024": -1
    do_jec_unc:
        '2016preVFP': false
        '2016postVFP': false
        '2017': false
        '2018': false
        '2022preEE': false
        '2022postEE': false
        "2023": false
        "2023BPix": false
        "2024": false
    do_jer_unc: # FIXME: Not validated yet for Run-3
        '2016preVFP': false
        '2016postVFP': false
        '2017': false
        '2018': false
        '2022preEE': false
        '2022postEE': false
        "2023": false
        "2023BPix": false
        "2024": false
    do_qgl_wgt: # NOTE: for nanoAODv15 Run2, it should be false for now
        '2016preVFP': true
        '2016postVFP': true
        '2017': true
        '2018': true
        # Run-3: Recommendation does not exists, yet.
        '2022preEE': false
        '2022postEE': false
        "2023": false
        "2023BPix": false
        "2024": false
    do_btag_wgt: # NOTE: for nanoAODv15 Run2, it should be false for now
        '2016preVFP': true
        '2016postVFP': true
        '2017': true
        '2018': true
        '2022preEE': false
        '2022postEE': false
        "2023": false
        "2023BPix": false
        "2024": false
    do_unc: # INFO: Use to turn on/off all unc variations. 
        # TO-DO: Need to implement it in the copperhead.
        '2016preVFP': false
        '2016postVFP': false
        '2017': false
        '2018': false
        '2022preEE': false
        '2022postEE': false
        "2023": false
        "2023BPix": false
        "2024": false
