hlt:
  2016preVFP:
  - IsoMu24
  - IsoTkMu24
  2016postVFP:
  - IsoMu24
  - IsoTkMu24
  '2017':
  - IsoMu27
  # - IsoMu24
  '2018':
  - Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8
  - IsoMu24
  - IsoMu20
  - IsoMu27
  - Ele23_Ele12_CaloIdL_TrackIdL_IsoVL
  - DoubleEle25_CaloIdL_MW
  - Ele32_WPTight_Gsf
  - Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ
  - Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ
  # - IsoMu27
  2016_RERECO:
  - IsoMu24
  - IsoTkMu24
  '2017_RERECO':
  - IsoMu27
  '2018_RERECO':
  - IsoMu24
  2022preEE:
  - IsoMu24
  2022postEE:
  - IsoMu24
