years:
  "2018PR":
    Data:
      total_lumi_pb: 59830.0
      data_A:
        skip_sample: False
        datasets:
          - /depot/cms/hmm/shar1172/Small_NanoAOD_ForValidtionPR/UL2018/SingleMuon_Run2018A
        lumi_pb: null
        das_request: null
        golden_json: data/lumimasks/Cert_314472-325175_13TeV_Legacy2018_Collisions18_JSON.txt
        references:
          ppd_summary_table: null
          golden_json_official: null

    DY:
        dy_M-100To200_aMCatNLO:
            skip_sample: False
            datasets:
                - /depot/cms/hmm/shar1172/Small_NanoAOD_ForValidtionPR/UL2018/DYJetsToLL_M-100to200_TuneCP5_13TeV-amcatnloFXFX-pythia8
            cross_section_pb: 233.8592627
            cross_section_source: None
            kfactor:
                value: 1.0
                source: NONE
            filter_efficiency: 1.0
            references:
                - "MG5_aMC@NLO FxFx"
