years:
    "2022preEE":
        Data:
            total_lumi_pb: 7980.4
            data_C:
                datasets:
                    - /Muon/Run2022C-16Dec2023-v1/NANOAOD
                    - /SingleMuon/Run2022C-16Dec2023-v1/NANOAOD
                lumi_pb: 5010.4 # e.g. 5.0
                das_request: "https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod/global&input=dataset%20status=*%20dataset=/Muon/Run2022C-16Dec2023-v1/NANOAOD"
                golden_json: data/lumimasks/Cert_Collisions2022_355100_362760_Golden.json
                references:
                    ppd_summary_table: https://docs.google.com/presentation/d/1F4ndU7DBcyvrEEyLfYqb29NGkBPs20EAnBxe_l7AEII/edit?slide=id.g289f499aa6b_2_52#slide=id.g289f499aa6b_2_52
                    golden_json_official: test

            data_D:
                datasets:
                    - /Muon/Run2022D-16Dec2023-v1/NANOAOD
                lumi_pb: 2970.0 # e.g. 3.1
                das_request: "https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod/global&input=dataset%20status=*%20dataset=/Muon/Run2022D-16Dec2023-v1/NANOAOD"
                golden_json: data/lumimasks/Cert_Collisions2022_355100_362760_Golden.json
                references:
                    ppd_summary_table: "Run 3 Data-taking twiki (2022D)"
                    golden_json_official: test
        DY:
            dyTo2L_M-50_0j:
                datasets:
                    - /DYto2L-2Jets_MLL-50_0J_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
                cross_section_pb: 5034.65
                cross_section_source: "amcatnlo"
                kfactor:
                    value: 1.0
                    source: "DY"
                filter_efficiency: 1.0
                references:
                    - "MG5_aMC@NLO FxFx"
                    - "PYTHIA8 CP5 tune"
                    - "amcatnlo"

            dyTo2L_M-50_1j:
                datasets:
                    - /DYto2L-2Jets_MLL-50_1J_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
                cross_section_pb: 952.29
                cross_section_source: "DY"
                kfactor:
                    value: 1.0
                    source: "DY"
                filter_efficiency: 1.0
                references:
                    - "MG5_aMC@NLO FxFx"
                    - "PYTHIA8 CP5 tune"
                    - "DY"

            dyTo2L_M-50_2j:
                datasets:
                    - /DYto2L-2Jets_MLL-50_2J_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
                cross_section_pb: 359.05
                cross_section_source: "DY"
                kfactor:
                    value: 1.0
                    source: "DY"
                filter_efficiency: 1.0
                references:
                    - "MG5_aMC@NLO FxFx"
                    - "PYTHIA8 CP5 tune"
                    - "DY"

            dy_M-50_aMCatNLO:
                datasets:
                    - /DYJetsToLL_M-50_TuneCP5_13p6TeV-madgraphMLM-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
                cross_section_pb: 5558.0
                cross_section_source: https://xsecdb-xsdb-official.app.cern.ch/xsdb/?columns=67108863&currentPage=0&pageSize=10&searchQuery=DAS%3DDYJetsToLL_M-50_TuneCP5_13p6TeV-madgraphMLM-pythia8
                kfactor:
                    value: 1.0
                    source: "DY"
                filter_efficiency: 1.0
                references:
                    - "MadGraph5_aMC"

            dyTo2L_M-50_incl:
                datasets:
                    - /DYto2L-2Jets_MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
                    - /DYto2L-2Jets_MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v1/NANOAODSIM
                notes: njets <= 2, not njets==2
                cross_section_pb: 6275.1 # 2091.7 * 3
                cross_section_source: https://twiki.cern.ch/twiki/bin/viewauth/CMS/MATRIXCrossSectionsat13p6TeV
                kfactor:
                    value: 1.0
                    source: "DY"
                filter_efficiency: 1.0
                references:
                    - "MadGraph5_aMC"

        Top:
            tt_inclusive:
                datasets:
                    - /TT_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
                    - /TT_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v2/NANOAODSIM
                cross_section_pb: 923.6
                cross_section_source: https://twiki.cern.ch/twiki/bin/view/LHCPhysics/TtbarNNLO
                notes: NNLO+NNLL top-quark-pair cross sections
                kfactor:
                    value: 1.0
                    source: "Top NNLO"
                filter_efficiency: 1.0
                references:
                    - "POWHEG "

        VV:
            ww_2l2nu:
                datasets:
                    - /WWto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
                    - /WWto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v2/NANOAODSIM
                cross_section_pb: 11.79
                cross_section_source: "SMP-25-013"
                kfactor:
                    value: 1.0
                    source: "POWHEG+MCFM"
                filter_efficiency: 1.0
                references:
                    - "POWHEG"

            wz_3lnu:
                datasets:
                    - /WZto3LNu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
                    - /WZto3LNu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v3/NANOAODSIM
                cross_section_pb: 5.31
                cross_section_source: "SMP-25-013"
                kfactor:
                    value: 1.0
                    source: "POWHEG+MCFM"
                filter_efficiency: 1.0
                references:
                    - "POWHEG"

            wz_2l2q:
                datasets:
                    - /WZto2L2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
                    - /WZto2L2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v2/NANOAODSIM
                cross_section_pb: 8.17
                cross_section_source: "SMP-25-013"
                kfactor:
                    value: 1.0
                    source: "POWHEG+MCFM"
                filter_efficiency: 1.0
                references:
                    - "POWHEG"

            zz:
                datasets:
                    - /ZZ_TuneCP5_13p6TeV_pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
                cross_section_pb: 12.17
                cross_section_source: "none"
                kfactor:
                    value: 1.0
                    source: "POWHEG+MCFM"
                filter_efficiency: 1.0
                references:
                    - "POWHEG"

        EWK:
            ewk_lljj:
                datasets:
                    - /EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
                cross_section_pb: 1.421
                cross_section_source: "computed using gen cross-section analyzer script"
                kfactor:
                    value: 1.00
                    source: "MadGraph5_aMC@NLO"
                filter_efficiency: 1.0
                references:
                    - "MadGraph5_aMC@NLO"

        Higgs:
            ggh_powhegPS:
                datasets:
                    - /GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v3/NANOAODSIM
                cross_section_pb: 0.0135096
                notes: "total cross-section = cross-section TIMES branching ratio = 51.96 * 2.6*10^{-4}"
                cross_section_source: https://twiki.cern.ch/twiki/bin/view/LHCPhysics/LHCHWG136TeVxsec_extrap#ggF_N3LO_QCD_NLO_EW
                kfactor:
                    value: 1.00
                    source: "HXSWG"
                branching_ratio: 2.6e-4
                br_source: "HXSWG"
                references:
                    - "POWHEG"

            vbf_powheg_dipole:
                datasets:
                    - /VBFHto2Mu_M-125_TuneCP5_withDipoleRecoil_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v3/NANOAODSIM
                cross_section_pb: 0.00105742
                notes: "total cross-section = cross-section TIMES branching ratio = 4.067*2.6*10^{-4}"
                cross_section_source: https://twiki.cern.ch/twiki/bin/view/LHCPhysics/LHCHWG136TeVxsec_extrap#VBF_approx_NNLO_QCD_NLO_EW
                kfactor:
                    value: 1.00
                    source: "HXSWG"
                branching_ratio: 2.6e-4
                br_source: "pdg"
                references:
                    - "POWHEG (with dipole recoil)"
