name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0   # REQUIRED for git diff

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the changed python code with pylint
      run: |
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$' || true)

        if [ -z "$CHANGED_FILES" ]; then
            echo "No Python files changed. Skipping pylint."
            exit 0
          fi

        echo "Running pylint on:"
        echo "$CHANGED_FILES"

        pylint $CHANGED_FILES
